### ISSUE TITLE
add volume to feed-cluster for the akka journal and snapshots

### ISSUE THREAD

**Issue by fabiofumarola** [DataToKnowledge/wheretolive-feed#18]

**Comment by fabiofumarola** [comment]
If I share the volume it returns an error with the native file system

```
akka.actor.ActorInitializationException: exception during creation
    at akka.actor.ActorInitializationException$.apply(Actor.scala:166)
    at akka.actor.ActorCell.create(ActorCell.scala:596)
    at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
    at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
    at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
    at akka.dispatch.Mailbox.run(Mailbox.scala:219)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Invalid argument
    at sun.nio.ch.FileChannelImpl.map0(Native Method)
    at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:925)
    at org.iq80.leveldb.impl.MMapLogWriter.<init>(MMapLogWriter.java:63)
    at org.iq80.leveldb.impl.Logs.createLogWriter(Logs.java:36)
    at org.iq80.leveldb.impl.VersionSet.initializeIfNeeded(VersionSet.java:106)
    at org.iq80.leveldb.impl.VersionSet.<init>(VersionSet.java:91)
    at org.iq80.leveldb.impl.DbImpl.<init>(DbImpl.java:178)
    at org.iq80.leveldb.impl.Iq80DBFactory.open(Iq80DBFactory.java:59)
    at akka.persistence.journal.leveldb.LeveldbStore$class.preStart(LeveldbStore.scala:112)
    at akka.persistence.journal.leveldb.LeveldbJournal.preStart(LeveldbJournal.scala:20)
    at akka.actor.Actor$class.aroundPreStart(Actor.scala:472)
    at akka.persistence.journal.leveldb.LeveldbJournal.aroundPreStart(LeveldbJournal.scala:20)
    at akka.actor.ActorCell.create(ActorCell.scala:580)
    ... 7 more


```
